[package]
name = "plain"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
pingora = { version = "0.6.0", features = ["lb","pingora-load-balancing", "pingora-proxy"] }
jemallocator = "0.5"
